### ISSUE TITLE
How to avoid the "jsPDF canvas plugin not installed" error (Webpack)

### ISSUE THREAD

**Issue by zedtux** [eKoopmans/html2pdf.js#225]
I'm migrating a Rails application to Webpack and I'm facing the alert message "jsPDF canvas plugin not installed" when I try to run `html2pdf()`.

Before to open this issue [I've asked on SO](https://stackoverflow.com/questions/55915990/error-jspdf-canvas-plugin-not-installed-with-html2pdf-js-and-webpack) but I had no luck.

Can you please help me on this?

**Comment by zedtux** [comment]
I finally got it working by aliasing html2pdf.js as html2pdf :

```javascript
environment.plugins.append('Provide', new webpack.ProvidePlugin({
  $: 'jquery',
  html2pdf: 'html2pdf.js',
  ...
}));
```

**Comment by eKoopmans** [comment]
Thanks for the follow-up @zedtux. I know in Rollup I need to define any externals/globals, similar to what you've shown, even if the package name is the same (e.g. `html2canvas: 'html2canvas'`).

In Webpack, did you need to configure that specifically because of the mismatch between the package name `html2pdf.js` and the function name `html2pdf`? Might be worth adding something to the readme about that. Thanks!

**Comment by zedtux** [comment]
> did you need to configure that specifically because of the mismatch between the package name html2pdf.js and the function name html2pdf?

Yes I needed it because we aren't using the import syntax In our app (no `import xxx from 'xxx'`) but also because of the `jsPDF canvas plugin not installed` error.

> Might be worth adding something to the readme about that.

💯
