### ISSUE TITLE
Corrupted .outputImg()

### ISSUE THREAD

**Issue by e58** [eKoopmans/html2pdf.js#226]
```js
html2pdf().from(el).outputImg().then((imgAsString) => {
   console.log(imgAsString);
});

/*
   output:
   <img src=​"data:​image/​jpeg;​base64,<base64_text>">​
*/

```

The image generated could not be loaded neither can the `base64_text` be decoded. I've tried changing the `element's` content but generated images are still corrupted.

**Comment by e58** [comment]
Resorted to using `html2canvas`

```js
html2canvas(el).then((canvas) => {
   let imgAsString = canvas.toDataURL('image/png', 1.0);
});

```

**Comment by eKoopmans** [comment]
Hi @e58, glad you found a solution that works for you.

`.outputImg()` by default returns the HTML image element, not a URI string, which is why you see `<img src=​"data:​image/​jpeg;​base64,<base64_text>">`. You could either access the `.src` of the returned HTML img, or use `.outputImg('datauristring')`, which returns that src directly.
