### ISSUE TITLE
Make new release 

### ISSUE THREAD

**Issue by joaofavara** [eKoopmans/html2pdf.js#249]
Please update npm release to use the latest repository version because the current release does not work with new relic (#220 )

**Comment by pmjonesg** [comment]
Bumping this as well, due to `es6-promisify` rollup problem that was fixed but does not seem to have been published yet.

For context, refering to this PR https://github.com/eKoopmans/html2pdf.js/pull/238.

@eKoopmans would be much appreciated if this could be published on npm when you get a chance.

**Comment by manimaran-kalimuthu** [comment]
Can be this released? It seems, its really required.

**Comment by subatomicglue** [comment]
I see the release 0.9.1 is 1 year old.  What's the status of this project?

**Comment by eKoopmans** [comment]
The status is that I have been away from it for far too long. I will be revisiting this soon and bringing some much-needed updates, starting with this version bump. Sorry for the wait.

**Comment by eKoopmans** [comment]
v0.9.2 is released, it should resolve issues with clashing Promises - let me know if that is still an issue. More fixes to come soon.

**Comment by subatomicglue** [comment]
You rock.  Thank you so much
