### ISSUE TITLE
PDF is cut when printing/downloading

### ISSUE THREAD

**Issue by VinceSanityyy** [eKoopmans/html2pdf.js#473]
I posted my question here

https://stackoverflow.com/questions/69122130/html2pdf-pdf-download-is-short-and-not-correct

I dont understand why it is cut and short when printing. Can you please help?

**Comment by TukuToi** [comment]
This is probably not happening if you use version 0.9 - try https://www.boreal-appliances.com/wp-content/themes/hello-theme-child/htmltoPDF.js and check
In my case, since they updated a few days ago everything went to 💩 on the instances we used it.

Reverting to 0.9 resolved the issues (which sound pretty similar to yours, PDF empty/cut off, missing parts, etc)

**Comment by frabanzo** [comment]
Hi @TukuToi how can I apply the advance usage to this version? https://www.boreal-appliances.com/wp-content/themes/hello-theme-child/htmltoPDF.js

**Comment by frabanzo** [comment]
Hi @TukuToi thank you very much for this, but I have a problem with the letter spacing of the content when I generate the file. Did you encounter that kind of issue? 

TIA

**Comment by VinceSanityyy** [comment]
Thanks for this one @TukuToi.

**Comment by eKoopmans** [comment]
Hi, I've had a few reports of things looking worse in v0.10. My guess is that it's due to changes in the dependency html2canvas - I'm putting together some tooling to try to see what's going on.

@VinceSanityyy @TukuToi I'll post here again when I have something up, would be helpful if you could test your issues against a few different versions.

**Comment by TukuToi** [comment]
@eKoopmans thanks!
You probably want to re-open this issue, since it was closed somehow (mistakenly probably)

I tested the issues I found with several versions and the only I found working was the one I had used originally, which is the one I link in my first comment on this issue (https://github.com/eKoopmans/html2pdf.js/issues/473#issuecomment-916882318)

**Comment by VinceSanityyy** [comment]
Hello @TukuToi . The cut issue is solved with your solution. Unfortunately i didint notice it removes the underline of the underlined words. (it is in the stackoverflow question ididint notice it earlier)

**Comment by TukuToi** [comment]
Given that is a way minor issue compared to the actual mess created with 0.10, I would suggest you open another issue for that, also because if it happens with 0.9, it means it is around since quite a while.

This way, they can resolve each issue one by one instead of bulk-debugging which never really goes well ;)

**Comment by VinceSanityyy** [comment]
Okay. I thought you got some idea about it. Thanks @TukuToi
