### ISSUE TITLE
Advance Usage on HTML2PDF version 0.8.1

### ISSUE THREAD

**Issue by frabanzo** [eKoopmans/html2pdf.js#474]
Hi, @eKoopmans thank you for your awesome library, I have some questions. Is version 0.8.1 can use advanced usage, like generating pdf files and save it to a local server?

Thank you very much in advance.

**Comment by TukuToi** [comment]
You can do that with version 0.9, that is for sure.
Version 0.8 is _very_ old, not sure you should even use that.
V0.9 is here https://gist.github.com/TukuToi/b24a34ba6354fe6cac557174dc07238d

**Comment by frabanzo** [comment]
Thanks for this man! @TukuToi

But I have some issues encountered when I use this, some header titles on the table are missing.

![image](https://user-images.githubusercontent.com/83382878/133028747-d65f03e5-399b-4348-b651-3e78d33be4a4.png)

**Comment by TukuToi** [comment]
Did you use 0.9? I am sure it is solved in there. If not, then the issue is due to the particular HTML markup you use.
Perhaps try a "plain vanilla" HTML Table first, then start making amendments towards what you want, to see when the issue starts, so you can report it here, and the authors can then look into it using a clear step by step approach to replicate?

**Comment by frabanzo** [comment]
Thank you very much @TukuToi, you're right the problem was on my HTML Table the whole dark background overlapped some header titles.

Thank you again, man!
